site_name: PHN CRM Help Centre
site_description: PHN CRM Help Centre

theme:
    name: "material"
    logo: "images/icon.png"

site_dir: docs/
docs_dir: src/

extra_css: [extra.css]

nav:
    - Home: 'index.md'
    - FAQ: 'faq.md'
    - Training: 'training.md'
    - Dynamics 365 App for Outlook: 'app-for-outlook.md'
    - Components:
        - Overview: 'components/overview.md'
        - GP Profile: 'components/gp-profile.md'
        - EwR (Risk) Framework: 'components/ewr.md'
        - Asset Register: 'components/asset-register.md'
        - Controlled Documents Register: 'components/controlled-docs.md'
        - Legislation: 'components/legislation.md'
        - Data Dictionary: 'components/data-dictionary.md'
        - Geography: 'components/geography.md'
    - Entities:
        - Account: 'entities/account.md'
        - Activity Category: 'entities/activity-category.md'
        - Agreement: 'entities/agreement.md'
        - Appointment: 'entities/appointment.md'
        - Call: 'entities/call.md'
        - Contact: 'entities/contact.md'
        - Contact Role: 'entities/contact-role.md'
        - Contact Role Type: 'entities/contact-role-type.md'
        - Controlled Document: 'entities/controlled-document.md'
        - CPRA: 'entities/cpra.md'
        - Definition: 'entities/definition.md'
        - Device: 'entities/device.md'
        - Device Allocation: 'entities/device-allocation.md'
        - Email: 'entities/email.md'
        - EULA: 'entities/eula.md'
        - Geographical (e.g. LGA): 'entities/geo.md'
        - Legislation: 'entities/legislation.md'
        - Marketing List: 'entities/marketing-list.md'
        - Risk: 'entities/risk.md'
        - Risk Action: 'entities/risk-action.md'
        - Software: 'entities/software.md'
        - Software License: 'entities/software-license.md'
        - Software Allocation: 'entities/software-allocation.md'
        - Task: 'entities/task.md'
        - User: 'entities/user.md'
    - Security Roles: 'sec-roles.md'
    - Settings: 
        - Auditing: 'settings/auditing.md'
        - Duplicate Detection: 'settings/duplicate-detection.md'
        - Timezones: 'settings/timezones.md'
    - Customization: 'customization.md'
    - Roadmap: 'roadmap.md'
    - Versioning: 'versioning.md'

markdown_extensions:
    - toc:
        permalink: true